project:
  type: website
  output-dir: docs

website:
  title: "Xetthecum Digital Ecocultural Mapping"
  search: false
  #google-analytics: 'G-MM4PBW09LS'
  page-footer: 
    right: "Contact" 
    background: "secondary"
    foreground: "primary"
  navbar:
    right:
      - href: https://imerss.github.io/xetthecum-storymap-story/Xetthecum-Storymap-Reknitted.html
        text: The Story of Xetthecum
      - href: about.qmd
        text: About
      - text: Explore
        menu:
          - text: Browse all Species
            href: taxa.qmd
          - text: Web of Life
            href: web-of-life.qmd
          - text: Cultural Values
            href: cultural-values.qmd
          - text: Ecological Communities
            href: ecological-values.qmd
          - text: Downloads
            href: data.qmd
      - href: resources.qmd
        text: Resources
format:
  html:
    theme: [flatly, css/theme-light.scss]
    css: [css/styles.css, https://use.fontawesome.com/releases/v6.0.0/css/all.css]
    include-in-header: header.html
