project:
  type: website
  output-dir: docs
  pre-render: generate_pages.R
  post-render: post_build.R

website:
  title: "Xetthecum Digital Ecocultural Mapping"
  search: false
  google-analytics: 'G-MM4PBW09LS'
  navbar:
    right:
      - href: https://imerss.github.io/xetthecum-storymap-story/Xetthecum-Storymap-Reknitted.html
        text: The Story of Xetthecum
      - text: About
        menu:
          - text: About the Project
            href: about.qmd
          - text: Meet the Team
            href: team.qmd
          - text: Research
            href: research.qmd
      - text: Explore
        menu:
          - text: Browse all Species
            href: taxa.qmd
          - text: Web of Life
            href: web-of-life.qmd
          - text: Cultural Values
            href: cultural-values.qmd
          - text: Ecological Communities
            href: ecological-values.qmd
          #- text: Downloads
          #  href: data.qmd
      - href: resources.qmd
        text: Resources
format:
  html:
    theme: [flatly, css/theme-light.scss]
    css: [css/styles.css, https://use.fontawesome.com/releases/v6.0.0/css/all.css]
    include-in-header: header.html
