project:
  type: website
  output-dir: docs

website:
  title: "Xetthecum Digital Ecocultural Mapping"
  search: false
  page-footer: 
    right: "Contact" 
    background: "secondary"
    foreground: "primary"
  navbar:
    right:
      - href: https://imerss.github.io/xetthecum-storymap-scrolly/Xetthecum-Storymap-Reknitted.html
        text: The Story of Xetthecum
      - href: about.qmd
        text: About
      - text: Explore
        menu:
          - text: How-to Tutorial
            href: about.qmd
          - text: Video Stories
            href: about.qmd
          - text: Image Gallery
            href: about.qmd
          - text: Browse all Species
            href: species.qmd
          - text: Web of Life
            href: web-of-life.qmd
          - text: Cultural Values
            href: cultural-values.qmd
          - text: Ecological Values
            href: about.qmd
      - href: resources.qmd
        text: Resources
    #google-analytics: 'G-01XD03JCPM'
format:
  html:
    theme: [flatly, css/theme-light.scss]
    css: [css/styles.css, css/modal.css, https://use.fontawesome.com/releases/v6.0.0/css/all.css]

